project_name              = "three-tier"
environment               = "dev"
owner                     = "platform-engineering"
aws_region                = "us-east-1"
vpc_cidr                  = "10.0.0.0/16"
availability_zones        = ["us-east-1a", "us-east-1b"]
public_subnet_cidrs       = ["10.0.1.0/24", "10.0.2.0/24"]
private_app_subnet_cidrs  = ["10.0.11.0/24", "10.0.12.0/24"]
private_data_subnet_cidrs = ["10.0.21.0/24", "10.0.22.0/24"]
enable_nat_gateway        = false
frontend_instance_type    = "t3.micro"
backend_instance_type     = "t3.micro"
bastion_instance_type     = "t3.micro"
frontend_min_size         = 1
frontend_max_size         = 3
frontend_desired_capacity = 1
backend_min_size          = 1
backend_max_size          = 3
backend_desired_capacity  = 1
key_pair_name             = ""
db_instance_class         = "db.t3.micro"
db_name                   = "appdb"
db_engine_version         = "15.4"
db_allocated_storage      = 20
db_max_allocated_storage  = 50
alarm_email               = "ops@example.com"
cpu_alarm_threshold       = 80