variable "project_name"              { type = string; default = "three-tier" }
variable "environment"               { type = string; default = "dev" }
variable "owner"                     { type = string; default = "platform-engineering" }
variable "aws_region"                { type = string; default = "us-east-1" }
variable "vpc_cidr"                  { type = string; default = "10.0.0.0/16" }
variable "availability_zones"        { type = list(string); default = ["us-east-1a","us-east-1b"] }
variable "public_subnet_cidrs"       { type = list(string); default = ["10.0.1.0/24","10.0.2.0/24"] }
variable "private_app_subnet_cidrs"  { type = list(string); default = ["10.0.11.0/24","10.0.12.0/24"] }
variable "private_data_subnet_cidrs" { type = list(string); default = ["10.0.21.0/24","10.0.22.0/24"] }
variable "enable_nat_gateway"        { type = bool;   default = false }
variable "frontend_instance_type"    { type = string; default = "t3.micro" }
variable "backend_instance_type"     { type = string; default = "t3.micro" }
variable "bastion_instance_type"     { type = string; default = "t3.micro" }
variable "frontend_min_size"         { type = number; default = 1 }
variable "frontend_max_size"         { type = number; default = 3 }
variable "frontend_desired_capacity" { type = number; default = 1 }
variable "backend_min_size"          { type = number; default = 1 }
variable "backend_max_size"          { type = number; default = 3 }
variable "backend_desired_capacity"  { type = number; default = 1 }
variable "key_pair_name"             { type = string; default = "" }
variable "db_instance_class"         { type = string; default = "db.t3.micro" }
variable "db_name"                   { type = string; default = "appdb" }
variable "db_username"               { type = string; default = "dbadmin"; sensitive = true }
variable "db_engine_version"         { type = string; default = "15.4" }
variable "db_allocated_storage"      { type = number; default = 20 }
variable "db_max_allocated_storage"  { type = number; default = 50 }
variable "alarm_email"               { type = string; default = "ops@example.com" }
variable "cpu_alarm_threshold"       { type = number; default = 80 }